In [3]:
import torch
import torch.nn as nn

In [4]:
a= torch.ones(5,5)
print(a)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [5]:
a= torch.ones(3,5)
print(a)
#sum and mean
sum=torch.sum(a, axis=1)
print(sum)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([5., 5., 5.])


In [6]:
a = torch.ones(5,1)
print(a)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])


In [7]:
a = torch.ones(5,1)
print(a.shape)
squeezed = torch.squeeze(a)
print(squeezed.shape)

torch.Size([5, 1])
torch.Size([5])


In [8]:
a = torch.ones(5,1)
print(a)
squeezed = torch.squeeze(a)
print(squeezed)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])
tensor([1., 1., 1., 1., 1.])


In [9]:
a= torch.ones(5,1)
squeezed = torch.squeeze(a)
print(squeezed.shape[0])

5


In [10]:
a= torch.ones(5,1)
squeezed = torch.squeeze(a)
unsqueezed = torch.unsqueeze(squeezed, dim=1)
print(unsqueezed.shape)

torch.Size([5, 1])


In [11]:
import torch
import torch.nn as nn

# neural network model
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.first_layer = nn.Linear(4, 6)
        self.second_layer = nn.Linear(6, 6)
        self.final_layer = nn.Linear(6, 2)

    def forward(self, x):
        x = self.first_layer(x)
        x = self.second_layer(x)
        x = self.final_layer(x)
        return x


model = MyModel()

# Example prediction
example_datapoint = torch.randn(1, 4)
prediction = model(example_datapoint)

print(prediction)


tensor([[-0.4102,  0.1785]], grad_fn=<AddmmBackward0>)


In [12]:
#8 Algorithms That Will Make You a God at AI/ML

In [13]:
#KNN
import numpy as np
from collections import Counter

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def predict(self, X):
        predictions = [self._predict(x) for x in X]
        return np.array(predictions)

    def _predict(self, x):
        # compute distances
        distances = [np.linalg.norm(x - x_train) for x_train in self.X_train]

        # get k nearest neighbors
        k_indices = np.argsort(distances)[:self.k]
        k_labels = [self.y_train[i] for i in k_indices]

        # majority vote
        most_common = Counter(k_labels).most_common(1)
        return most_common[0][0]

# sample dataset
X_train = np.array([[1,2], [2,3], [3,3], [6,9], [7,7], [8,6]])
y_train = np.array([0, 0, 0, 1, 1, 1])

knn = KNN(k=3)
knn.fit(X_train, y_train)

X_test = np.array([[5,5]])
prediction = knn.predict(X_test)

print("Prediction:", prediction)



Prediction: [1]


In [14]:
#SVM
from sklearn import svm
import numpy as np

# dataset
X = np.array([[1,2], [2,3], [3,3], [6,5], [7,7], [8,6]])
y = np.array([0, 0, 0, 1, 1, 1])

# create SVM classifier
model = svm.SVC(kernel='linear')

# train
model.fit(X, y)

# predict
prediction = model.predict([[5, 5]])
print("Prediction:", prediction)
svm.SVC(kernel='linear')   # straight line
svm.SVC(kernel='')      # curved boundary (most used)
svm.SVC(kernel='poly')     # polynomial
svm.SVC(kernel='sigmoid')



Prediction: [1]


SVC(kernel='sigmoid')

In [15]:
#NBA
import numpy as np

class NaiveBayes:
    def fit(self, X, y):
        self.classes = np.unique(y)
        self.mean = {}
        self.var = {}
        self.priors = {}

        for c in self.classes:
            X_c = X[y == c]
            self.mean[c] = X_c.mean(axis=0)
            self.var[c] = X_c.var(axis=0)
            self.priors[c] = X_c.shape[0] / X.shape[0]

    def predict(self, X):
        return np.array([self._predict(x) for x in X])

    def _predict(self, x):
        posteriors = []

        for c in self.classes:
            prior = np.log(self.priors[c])
            likelihood = np.sum(np.log(self._pdf(c, x)))
            posterior = prior + likelihood
            posteriors.append(posterior)

        return self.classes[np.argmax(posteriors)]

    def _pdf(self, c, x):
        mean = self.mean[c]
        var = self.var[c]
        numerator = np.exp(- (x - mean) ** 2 / (2 * var))
        denominator = np.sqrt(2 * np.pi * var)
        return numerator / denominator

X = np.array([[1,2], [2,3], [3,3], [6,5], [7,7], [8,6]])
y = np.array([0, 0, 0, 1, 1, 1])

nb = NaiveBayes()
nb.fit(X, y)

prediction = nb.predict(np.array([[5,5]]))
print("Prediction:", prediction)


Prediction: [1]


In [16]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X, y)
print(model.predict([[5,5]]))


[1]


In [17]:
import numpy as np
from collections import Counter

class DecisionTree:
    def __init__(self, max_depth=3):
        self.max_depth = max_depth

    def fit(self, X, y):
        self.tree = self._grow_tree(X, y, depth=0)

    def predict(self, X):
        return np.array([self._traverse_tree(x, self.tree) for x in X])

    def _grow_tree(self, X, y, depth):
        if depth >= self.max_depth or len(set(y)) == 1:
            return Counter(y).most_common(1)[0][0]

        feat, thresh = self._best_split(X, y)
        left_idx = X[:, feat] < thresh
        right_idx = X[:, feat] >= thresh

        left = self._grow_tree(X[left_idx], y[left_idx], depth+1)
        right = self._grow_tree(X[right_idx], y[right_idx], depth+1)

        return (feat, thresh, left, right)

    def _best_split(self, X, y):
        best_feat, best_thresh = 0, X[:,0].mean()
        return best_feat, best_thresh

    def _traverse_tree(self, x, node):
        if not isinstance(node, tuple):
            return node
        feat, thresh, left, right = node
        if x[feat] < thresh:
            return self._traverse_tree(x, left)
        return self._traverse_tree(x, right)


In [18]:
X = np.array([[1,2], [2,3], [3,3], [6,5], [7,7], [8,6]])
y = np.array([0, 0, 0, 1, 1, 1])

tree = DecisionTree(max_depth=2)
tree.fit(X, y)

print(tree.predict(np.array([[5,5]])))
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X, y)
print(model.predict([[5,5]]))



[1]
[1]


In [19]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np

X = np.array([[1,2], [2,3], [3,3], [6,5], [7,7], [8,6]])
y = np.array([0, 0, 0, 1, 1, 1])

model = RandomForestClassifier(n_estimators=100)
model.fit(X, y)

prediction = model.predict([[5,5]])
print("Prediction:", prediction)



Prediction: [1]


In [20]:
#linear regression
import numpy as np

class LinearRegression:
    def fit(self, X, y, lr=0.01, epochs=1000):
        n, d = X.shape
        self.w = np.zeros(d)
        self.b = 0

        for _ in range(epochs):
            y_pred = X @ self.w + self.b
            dw = (1/n) * X.T @ (y_pred - y)
            db = (1/n) * np.sum(y_pred - y)

            self.w -= lr * dw
            self.b -= lr * db

    def predict(self, X):
        return X @ self.w + self.b


In [21]:
#logistic
class LogisticRegression:
    def fit(self, X, y, lr=0.1, epochs=1000):
        n, d = X.shape
        self.w = np.zeros(d)
        self.b = 0

        for _ in range(epochs):
            z = X @ self.w + self.b
            y_pred = 1 / (1 + np.exp(-z))

            dw = (1/n) * X.T @ (y_pred - y)
            db = (1/n) * np.sum(y_pred - y)

            self.w -= lr * dw
            self.b -= lr * db

    def predict(self, X):
        z = X @ self.w + self.b
        probs = 1 / (1 + np.exp(-z))
        return (probs >= 0.5).astype(int)


In [43]:
!git --version


git version 2.47.0.windows.1
