<a href="https://colab.research.google.com/github/riteshbhadana/practice/blob/main/pytorch_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# It’s a beginner-friendly PyTorch crash course that walks through building a neural network end-to-end.

Tiny summary:

Introduces PyTorch tensors and GPU basics

Explains autograd and how gradients work

Builds a simple neural network model

Shows a full training loop (loss + optimizer)

Demonstrates evaluation & prediction

Emphasizes practical coding over theory
#By Neural Nine

In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [5]:
torch.cuda.device_count()


1

In [6]:
torch.cuda.get_device_name(0)


'Tesla T4'

# Tensors

In [7]:
torch.cuda.device(0)

In [8]:
import numpy as np


In [9]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
tensor = torch.tensor([[1,2,3],[4,5,6]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
arr*5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [12]:
tensor*5

tensor([[ 5, 10, 15],
        [20, 25, 30]])

In [13]:
arr.sum()

np.int64(21)

In [15]:
tensor.sum()

tensor(21)

In [16]:
tensor=torch.from_numpy(arr)

In [17]:
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
torch.ones((2,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
np.random.random((2,4))

array([[0.27245689, 0.6371319 , 0.53359151, 0.51730596],
       [0.07409565, 0.39861869, 0.01595073, 0.98679116]])

In [23]:
torch.rand((2,4))

tensor([[0.8220, 0.0279, 0.1065, 0.8934],
        [0.3095, 0.9409, 0.0255, 0.5403]])

In [24]:
arr.shape

(2, 3)

In [25]:
arr.dtype

dtype('int64')

In [26]:
arr.device

'cpu'

In [27]:
tensor.shape

torch.Size([2, 3])

In [28]:
tensor.dtype

torch.int64

In [29]:
arr.device

'cpu'

In [30]:
tensor.to('cuda')

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [31]:
tensor=tensor.to('cuda')

In [35]:
tensor.sum()

tensor(21, device='cuda:0')

In [36]:
tensor.cpu().numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

.to(device)

# Autograd

In [46]:
a = torch.tensor([2.,3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

f = 3 * a**3 - b**2


In [47]:
f

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [48]:
f.backward(gradient=torch.tensor([1,1]))

In [49]:
print(a.grad)


tensor([36., 81.])


In [50]:
print(b.grad)

tensor([-12.,  -8.])


# Loading dataset

In [59]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [61]:
X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [62]:
X_train_scaled

array([[ 1.18130325,  0.16360046,  1.14611449, ...,  1.21474965,
         0.26571916, -0.01490544],
       [ 3.30452147, -0.43443024,  3.39090674, ...,  2.47686389,
         1.26745941,  0.22536902],
       [ 2.13504833,  0.70942214,  2.16572709, ...,  1.96527875,
         1.48793812,  0.89996511],
       ...,
       [-0.50478181, -0.65750519, -0.51527845, ..., -0.41803407,
        -0.44524481, -0.42288825],
       [ 0.88041938,  0.65958625,  0.81720721, ...,  1.29439763,
         0.51016295, -0.4438518 ],
       [ 1.55031176,  2.24958852,  1.72170225, ...,  1.22853487,
        -0.12571044,  0.88921458]])

In [63]:
y_train

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,

In [84]:
X_train_scaled_tensor = torch.from_numpy(X_train_scaled).float()
X_test_scaled_tensor = torch.from_numpy(X_test_scaled).float()
y_train_tensor = torch.from_numpy(y_train).float().unsqueeze(1)
y_test_tensor = torch.from_numpy(y_test).float().unsqueeze(1)

In [85]:
train_dataset = TensorDataset(X_train_scaled_tensor, y_train_tensor)


In [86]:
X_train_scaled_tensor.shape

torch.Size([455, 30])

In [87]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# Neural Network

In [95]:
class BCNet(nn.Module):
  def __init__(self):
    super(BCNet, self).__init__()

    self.fc1 = nn.Linear(30, 64)
    self.fc2 = nn.Linear(64, 32)
    self.fc3 = nn.Linear(32, 1)

    self.dropout = nn.Dropout(0.5)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.dropout(x)
    x = F.sigmoid(self.fc3(x))

    return x


In [96]:
criterion = nn.BCELoss()
model = BCNet()
optimizer = optim.Adam(model.parameters(), lr=0.001)


In [90]:
epochs = 20

for epoch in range(epochs):
  model.train()
  running_loss= 0.0

  for x_batch, y_batch in train_loader:
    optimizer.zero_grad()
    pred = model(x_batch)
    loss = criterion(pred, y_batch)

    loss.backward()
    optimizer.step()

    running_loss += loss.item()

  print(f'Epoch {epoch+1}, Loss was {running_loss/len(train_loader)}')

Epoch 1, Loss was 0.6032044529914856
Epoch 2, Loss was 0.44463044007619223
Epoch 3, Loss was 0.26966094772020976
Epoch 4, Loss was 0.164014217009147
Epoch 5, Loss was 0.12110427344838778
Epoch 6, Loss was 0.09404071470101674
Epoch 7, Loss was 0.08198539608468612
Epoch 8, Loss was 0.09618797606478134
Epoch 9, Loss was 0.0702671512340506
Epoch 10, Loss was 0.06777309731890759
Epoch 11, Loss was 0.060909864989419776
Epoch 12, Loss was 0.05930530019104481
Epoch 13, Loss was 0.055563306001325447
Epoch 14, Loss was 0.054444094250599546
Epoch 15, Loss was 0.04834974557161331
Epoch 16, Loss was 0.04676834604082008
Epoch 17, Loss was 0.06129679953058561
Epoch 18, Loss was 0.04552666395902634
Epoch 19, Loss was 0.04237672382344802
Epoch 20, Loss was 0.041491817217320204


In [91]:
print(type(X_test_scaled_tensor))


<class 'torch.Tensor'>


In [93]:
with torch.no_grad():
    model.eval()
    preds = model(X_test_scaled_tensor)
    loss = criterion(preds, y_test_tensor).item()
    accuracy = ((preds >= 0.5) == y_test_tensor).float().mean().item()


In [97]:
accuracy

1.0